### ISSUE TITLE
Accessing summary stats

### ISSUE THREAD

**Issue by gokceneraslan** [CaoTianze/pandasgwas#1]
Thanks for this super cool package! I am trying to access the sumstats of study GCST007320:

```python
from pandasgwas.summary_statistics import search, browser, download, parse

search_DF = search(study_accession_id='GCST007320')
```

but search_DF seems to be empty. Any ideas on why it might be failing?

**Comment by CaoTianze** [comment]
Thank you for the issue. Currently, this package supports searching and reading harmonised data of summary statistics. I checked the FTP URL of the GCST007320 (https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST007001-GCST008000/GCST007320/）. It does not currently support reads.
